version: "3.8"

services:
  demo-app:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    environment:
      - DATABASE_URL=mongodb://demo-mongo/27017/app-db
    volumes:
      - ./myapp:/app
    networks:
      - demo-network
    depends_on:
      - demo-mongo

  demo-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - demo-network
    volumes:
      - demo-mongo-data:/data/db

  demo-mongo-express:
    image: mongo-express:latest
    ports:
      - "5000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=demo-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - demo-network
    depends_on:
      - demo-mongo

  demo-postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - demo-postgres-data:/var/lib/postgresql/data
    networks:
      - demo-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - demo-postgresql
    volumes:
      - demo-pgadmin_data:/var/lib/pgadmin
    networks:
      - demo-network

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # Redis protocol
      - "6012:8001" # RedisInsight (if included in your stack)
    environment:
      - REDIS_ARGS=--save 900 1
    volumes:
      - demo-redis-data:/var/lib/redis-stack
    networks:
      - demo-network

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - demo-rabitmq-data:/var/lib/rabbitmq
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  demo-mongo-data:
  demo-postgres-data:
  demo-pgadmin_data:
  demo-redis-data:
  demo-rabitmq-data:
